name: Deploy frontend application

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3     
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
      - name: Prepare the docker-compose run
        run: |
          ls -l
          ls -l my-website
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./my-website
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-website:latest
          
      - name: Generate docker-compose.yml
        run: |
          echo "version: '3.8'" > docker-compose.yml
          echo "services:" >> docker-compose.yml
          echo "  my-website:" >> docker-compose.yml
          echo "    image: ${DOCKER_HUB_USERNAME}/my-website:latest" >> docker-compose.yml
          echo "    ports:" >> docker-compose.yml
          echo "      - '80:80'" >> docker-compose.yml
          echo "  todo-app:" >> docker-compose.yml
          echo "    image: benoitg/todomvc-app:latest" >> docker-compose.yml
          echo "    ports:" >> docker-compose.yml
          echo "      - '3000:3000'" >> docker-compose.yml
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          
      - name: Copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ubuntu/frontend"
          
      - name: Docker compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/frontend
            echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            docker compose down
            docker compose pull
            docker compose up -d
            rm -rf /home/ubuntu/frontend
